### ISSUE TITLE
webpack and webworkify

### ISSUE THREAD

**Issue by meandavejustice** [a-vis/gl-waveform#21]
This module doesn't work with webpack because of the `webworkify` dependency.

In order to get it to work, [line 26 in `create-storage.js`](https://github.com/audio-lab/gl-waveform/blob/master/src/create-storage.js#L26) needs this adjustment

``` js
let worker = workify(require('./worker'));
```

``` js
let worker = workify(require.resolve('./worker'));
```

Along with requiring `webworkify-webpack` instead of `webworkify`.

It would be nice if support for both could be added, though the extra dependency is annoying...

**Comment by dfcreative** [comment]
Awesome, thanks for the PR!
In the meantime I think I got a new method of getting waveform stats O(c), so we can get rid of webworker at all. Please stay tuned!

**Comment by meandavejustice** [comment]
@dfcreative Woah awesome! looking forward to seeing that

**Comment by dy** [comment]
With new bundle it works.
