### ISSUE TITLE
Error thrown from gl-util setProgram

### ISSUE THREAD

**Issue by owenhoskins** [a-vis/gl-waveform#24]
Hello, I came across this very nice project yesterday, great stuff! I am attempting to dive into it by creating a playground with a webpack / reactjs stack but I am running into issues which I haven't been able to resolve.

#21 helped me with a webpack issue but I soon ran into this when trying to hook up the waveform:

```
    var waveform = createWaveform({
      autostart: false,
      palette: ['black', 'white'],
      scale: 2,
      log: false,
      bufferSize: 44100*5
    });
```

Warning: `WebGL: INVALID_VALUE: shaderSource: string not ASCII` and `Uncaught Error: ERROR: 0:? : '' : syntax error` thrown by [line 41 in setProgram](https://github.com/dfcreative/gl-util/blob/master/program.js#L41) in `gl-util`

I took a look around gl-util but I must admit I am way out of my depth here... Does this error raise any flags for you? Any pointers would be appreciated!

**Comment by dfcreative** [comment]
@owenhoskins I will try to look at this today evening, loaded with work, stay tuned.
I was planning to transition to regl anyways.

**Comment by owenhoskins** [comment]
@dfcreative: Thanks for the rapid response. I came across your earlier version in the [start app](https://github.com/scrapjs/start-app) and was able to get off the ground with that. Regl looks like a lot of fun to work with, glad you mentioned it!

**Comment by dy** [comment]
Not relevant anymore.
